from confidence import calculate_confidence
from parser import extract_errors
from rule_engine import check_known_errors
from analyzer import analyze
from report_generator import save_report
from categorizer import categorize
from database import find_similar
from notifier import send_alert


def investigate(
    log_path,
    repository="Unknown",
    workflow="Unknown",
    run_id="Unknown",
    workflow_url="N/A"
):

    print("=" * 60)
    print("DEVOPS INVESTIGATION AGENT")
    print("=" * 60)

    print(f"\nRepository : {repository}")
    print(f"Workflow   : {workflow}")
    print(f"Run ID     : {run_id}")
    print(f"Workflow URL : {workflow_url}")

    # Extract errors
    errors = extract_errors(log_path)

    # Category
    category = categorize(errors)

    # Confidence
    confidence = calculate_confidence(errors)

    print(f"\nCategory   : {category}")
    print(f"Confidence : {confidence}%")

    # Check previous incidents
    previous = find_similar(errors)

    if previous:

        print("\n" + "=" * 60)
        print("SIMILAR INCIDENT FOUND")
        print("=" * 60)

        print(f"\nLast Seen      : {previous[0]}")
        print(f"Category       : {previous[1]}")
        print(f"Root Cause     : {previous[2]}")
        print(f"Suggestions    :\n{previous[3]}")

        print("\nContinuing investigation...\n")

    print("\nExtracted Errors:\n")
    print(errors)

    print("\nChecking Knowledge Base...\n")

    result = check_known_errors(errors)

    if result:

        print("KNOWN ERROR DETECTED\n")

        print("Root Cause:")
        print(result["root_cause"])

        print("\nSuggested Actions:")

        for item in result["suggestions"]:
            print("-", item)

        report = save_report(
            repository,
            workflow,
            run_id,
            workflow_url,
            category,
            errors,
            result["root_cause"],
            result["suggestions"],
            log_path
        )

        send_alert(
            category,
            result["root_cause"],
            result["suggestions"]
        )

        print(f"\nReport saved to: {report}")

    else:

        print("UNKNOWN ERROR")
        print("Sending to Ollama...\n")

        response = analyze(errors)

        print(response)

        report = save_report(
            repository,
            workflow,
            run_id,
            workflow_url,
            category,
            errors,
            "Generated by Ollama",
            [response],
            log_path
        )

        send_alert(
            category,
            "Generated by Ollama",
            [response]
        )

        print(f"\nReport saved to: {report}")


if __name__ == "__main__":

    investigate("samples/docker_failure.log")
